#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Exception-Class
Version  : 1.44
Release  : 10
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.44.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Exception-Class-1.44.tar.gz
Summary  : 'A module that allows you to declare real exception classes in Perl'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Exception-Class-license
Requires: perl-Exception-Class-man
BuildRequires : perl(Class::Data::Inheritable)
BuildRequires : perl(Devel::StackTrace)

%description
# NAME
Exception::Class - A module that allows you to declare real exception classes in Perl

%package license
Summary: license components for the perl-Exception-Class package.
Group: Default

%description license
license components for the perl-Exception-Class package.


%package man
Summary: man components for the perl-Exception-Class package.
Group: Default

%description man
man components for the perl-Exception-Class package.


%prep
%setup -q -n Exception-Class-1.44

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Exception-Class
cp LICENSE %{buildroot}/usr/share/doc/perl-Exception-Class/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Exception/Class.pm
/usr/lib/perl5/site_perl/5.26.1/Exception/Class/Base.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Exception-Class/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Exception::Class.3
/usr/share/man/man3/Exception::Class::Base.3
